[package]
name = "silk-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.12.5", features = [ "json"] }
scraper = "0.20.0"
tokio = { version = "1.39.2", features = ["full"] }
